// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNxx19VLl6E-TfRNojLdQs_S1Hq_eq5Fk',
    appId: '1:862953136740:web:8fddd4c5a0a65cefab7571',
    messagingSenderId: '862953136740',
    projectId: 'gateflow-ss',
    authDomain: 'gateflow-ss.firebaseapp.com',
    storageBucket: 'gateflow-ss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0suPxQiOAsjBv8ZxggWB9a1A3Iya_jU',
    appId: '1:862953136740:android:8483d020de370fc7ab7571',
    messagingSenderId: '862953136740',
    projectId: 'gateflow-ss',
    storageBucket: 'gateflow-ss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCECAg2bYH1h84n4rm1EZz3R9RtLVm9MVo',
    appId: '1:862953136740:ios:4921ff4a802608d2ab7571',
    messagingSenderId: '862953136740',
    projectId: 'gateflow-ss',
    storageBucket: 'gateflow-ss.firebasestorage.app',
    iosBundleId: 'com.example.gateflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCECAg2bYH1h84n4rm1EZz3R9RtLVm9MVo',
    appId: '1:862953136740:ios:4921ff4a802608d2ab7571',
    messagingSenderId: '862953136740',
    projectId: 'gateflow-ss',
    storageBucket: 'gateflow-ss.firebasestorage.app',
    iosBundleId: 'com.example.gateflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNxx19VLl6E-TfRNojLdQs_S1Hq_eq5Fk',
    appId: '1:862953136740:web:636b78ab225da5bfab7571',
    messagingSenderId: '862953136740',
    projectId: 'gateflow-ss',
    authDomain: 'gateflow-ss.firebaseapp.com',
    storageBucket: 'gateflow-ss.firebasestorage.app',
  );
}
